#!/bin/bash

# Get the colors generated by pywal
color1=$(sed -n '1p' ~/.cache/wal/colors)
color2=$(sed -n '2p' ~/.cache/wal/colors)
color3=$(sed -n '3p' ~/.cache/wal/colors)

# Update Cava's configuration file
sed -i "s/^gradient_color_1 = .*/gradient_color_1 = $color1/" ~/.config/cava/config
sed -i "s/^gradient_color_2 = .*/gradient_color_2 = $color2/" ~/.config/cava/config
sed -i "s/^gradient_color_3 = .*/gradient_color_3 = $color3/" ~/.config/cava/config

# Get the current terminal window ID
kitty_id=$(kitty @ ls | jq -r '.[].tabs[].windows[] | select(.foreground_processes[].cmdline | index("cava")) | .id')

# If Cava is running, restart it in the same terminal
if [ -n "$kitty_id" ]; then
  kitty @ close-window --match id:$kitty_id
  kitty @ launch --match id:$kitty_id cava
else
  # Otherwise, just launch cava
  kitty @ launch cava
fi

